
#多配置文件
server:
  port: 8001

spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/
#    spring.resources.static-locations=classpath:/

#指定输出界别
logging:

  level:
    org.springframework: #添加 security的日志输出
          data: DEBUG
          security: DEBUG
  path: D:/log/ #指定路径
  #file: springboot.log #指定日志文件
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  # mapper-locations: classpath:/mapper/*Mapper.xml
  mapper-location: classpath:/cn/com/demo/dao/*/*/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.com.demo.dao.*.entity #com.yourpackage.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#  application:
#    name: user
#logging:
#    #level: debug
#    path: D:/log/
#dubbo:
#  scan:
#    base-packages: cn.com.boostarp.service,cn.com.bluemoon.service
#  application:
#    id: dubbo-provider-demo
#    name: dubbo-provider-demo
#    owner: niejian
#  registry:
#    id: zk_address
#    address: zookeeper://192.168.240.15:2181?backup=192.168.240.15:2182,192.168.240.15:2183
#    #address: zookeeper://192.168.240.15:2181
#    protocol: zookeeper
#    timeout: 600000
#不向注册中心注册自己
#eureka:
#  client:
##    register-with-eureka: false
##    fetch-registry: false #不需要检索服务
#    service-url:
#      defaultZone: http://localhost:8088/eureka/
#  instance:
#    hostname: user

#  protocol:
#    name: dubbo
